# Platform: Kubernetes (Helm template)
# Purpose: Intentionally insecure templated workload. DO NOT APPLY.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fcs-demo
  labels:
    app: {{ .Release.Name }}-fcs-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fcs-demo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fcs-demo
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      hostPID: {{ .Values.hostPID }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: true
      securityContext:
        runAsUser: {{ .Values.podSecurityContext.runAsUser }}
        runAsNonRoot: {{ .Values.podSecurityContext.runAsNonRoot }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              hostPort: 80
          securityContext:
            privileged: {{ .Values.securityContext.privileged }}
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
            capabilities:
              add:
                {{- toYaml .Values.securityContext.capabilities.add | nindent 16 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DB_PASSWORD
              value: {{ .Values.secrets.dbPassword | quote }}
            - name: API_TOKEN
              value: {{ .Values.secrets.apiToken | quote }}
          volumeMounts:
            - name: host-root
              mountPath: /host
      volumes:
        - name: host-root
          hostPath:
            path: /
            type: Directory
